# main.R
library(dplyr)
library(stringr)
library(readr)
library(here)
library(ggplot2)
library(patchwork)
library(tidyverse)
library(lme4)
library(broom.mixed)
library(forcats)

source(here("src", "00_prepare_data.R"))
source(here("src", "01_make_subsets.R"))
source(here("src", "02_standard_plots.R"))
source(here("src", "03_subset_plots.R"))
source(here("src", "04_models.R"))
# source(here("src", "04_model_plots.R"))